In [4]:
my_list = [1,2,3]

In [5]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((5,1)) # Example of a 2D-array 
                #5 represents no. of rows
                #1 reperesents no. of columns

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [20]:
np.zeros((2,2)) 

array([[0., 0.],
       [0., 0.]])

In [21]:
np.zeros(4) #here it is a 1D array ,for 2D arrays we have to use a tuple(no_of_rows,no_of_columns)

array([0., 0., 0., 0.])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.linspace(0,5,10) #1D-array as there is only one open-close third bracket
                    #Here 10 represents no.of points u want 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(5) #returns a 1-D array with 5 random no.s between 0 and 1

array([0.18612348, 0.33725827, 0.54839551, 0.41967861, 0.35037077])

In [31]:
np.random.rand(10,2)

array([[0.40817868, 0.6912925 ],
       [0.32468191, 0.54038896],
       [0.65888661, 0.00119725],
       [0.69060238, 0.88866523],
       [0.10081326, 0.67102221],
       [0.86248123, 0.22725401],
       [0.91152021, 0.7840449 ],
       [0.04072568, 0.761581  ],
       [0.41053054, 0.99600404],
       [0.40595636, 0.00890758]])

In [33]:
np.random.randn(2) #randn gives us random no. from a gaussian dsitribution

array([ 0.5926106 , -1.10937925])

In [34]:
np.random.randn(2,3)

array([[-1.06229731,  2.36272546,  1.9718555 ],
       [ 1.95905053, -0.92839795, -1.61593028]])

In [38]:
np.random.randint(1,100,10)

array([51, 48, 58, 57, 28, 77, 55, 12, 70, 37])

In [45]:
arr = np.arange(25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
ranarr = np.random.randint(0,50,10)

In [48]:
ranarr

array([ 3, 30, 34, 16,  1, 23, 31, 42, 11, 41])

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
ranarr

array([ 3, 30, 34, 16,  1, 23, 31, 42, 11, 41])

In [56]:
ranarr.max()

42

In [57]:
ranarr.min()

1

In [58]:
ranarr.argmax()

7

In [59]:
ranarr.argmin()

4

In [60]:
arr.shape

(25,)

In [61]:
arr.dtype

dtype('int32')

INDEXING IN ARRAYS

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
arr1 = np.arange(0,10)

In [64]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr1[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr1[0:5]

array([0, 1, 2, 3, 4])

In [67]:
arr1[0:5] = 100

In [68]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [70]:
arr = np.arange(0,11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
slice_of_arr = arr[0:6]

In [73]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [74]:
slice_of_arr[:] = 99

In [75]:
slice_of_arr


array([99, 99, 99, 99, 99, 99])

In [76]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
arr_copy = arr.copy()

In [78]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr_copy[:] =100

In [80]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [81]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [82]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [83]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [84]:
arr_2d[0][0]

5

In [85]:
arr_2d[0]

array([ 5, 10, 15])

In [86]:
arr_2d[2,1]

40

In [89]:
arr_2d[0,2]

15

In [90]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [91]:
arr_2d[:2]  #slicing upto row 2 that is row 0 and 1

array([[ 5, 10, 15],
       [20, 25, 30]])

In [92]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [93]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [94]:
arr = np.arange(1,11)

In [95]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
bool_arr = arr >5

In [98]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [99]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [100]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [101]:
arr[arr < 3]

array([1, 2])

In [102]:
arr[arr == 5]

array([5])

In [111]:
arr_2d = np.arange(50).reshape(5,10)

In [112]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [118]:
arr_2d[2:3,1:5]

array([[21, 22, 23, 24]])